blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/vnali/craft-studio/discussions/new?category=ideas
    about: Start a new discussion about your idea
  - name: Documentation
    url: https://github.com/vnali/studio-plugin-docs
    about: Read the documentation
  - name: Q&A
    url: https://github.com/vnali/craft-studio/discussions/new?category=q-a
    about: Ask a question
  - name: Send an email
    url: https://github.com/vnali/studio-plugin-docs#contact
    about: Send an email to vnali.dev@gmail.com
  - name: Craft Discord
    url: https://craftcms.com/discord
    about: Contact me on the Discord vnali -vnali#8759-